[project]
name = "dz-customers-clustering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clickhouse-connect",
    "kmodes",
    "matplotlib",
    "numpy",
    "pandas",
    "python-dotenv",
    "scikit-learn",
    "seaborn",
]
